# Generated by Django 3.2.9 on 2021-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211130_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=6, default='', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates_lng',
            field=models.DecimalField(decimal_places=6, default='', max_digits=9),
            preserve_default=False,
        ),
    ]
