# Generated by Django 3.2.9 on 2021-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211208_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
