# Generated by Django 3.2.9 on 2021-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20211208_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
