# Generated by Django 3.2.9 on 2021-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
